name: 'Deploy Firebase (not just) Cloud Functions'
author: 'ProgrammerPeter2'
description: 'A GitHub Action to deploy to Firebase Cloud Functions'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'black'
